### ISSUE TITLE
http or https arctos.db.org

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1066]
Hi folks,
I need to create links to the new website through our msb portal, but I get an error when I try to search on the link google returns. I take it this is an http vs https problem. Is this going to be resolved? Which will be the permanent url?

Also, I am getting a broken link for Arctos as an Ecosystem.

**Comment by mkoo** [comment]
Yes, this has been a persistent issue. It is in part to do with the SSL
certificate (http vs https). Hopefull that will be done soon

The other part will require Dusty to do a Find/replace so that we have
hyphens not underscores between words. But maybe Dusty needs to chat with
Philip about that reconciliation.

I'll get a party started.
Sorry for all the inconvenience! I thought a large part of this was already
resolved!
MK

**Comment by tigerhawkvok** [comment]
Yeah, the cert is part of it, but for the other part @campmlc see https://github.com/ArctosDB/documentation-wiki/issues/31#issuecomment-286876413 . I just applied https://github.com/ArctosDB/documentation-wiki/commit/c7e7d209cc9b08d588579fa22d57e15a978fd7e9 which should fix bad anchors when the link is the same ... need to think of something clever for the whole URLs though

**Comment by dustymc** [comment]
@campmlc when forming links http should always be safe.

@mkoo @tigerhawkvok @ccicero the underbar/dash thing (and broken links in general) should no longer be an issue - I've rebuilt the documentation handler, all links are now going through /manage/field-level documentation.

Everything in the code has an Arctos-side doc entry, all links including anchors work correctly, and everything links to something in the docs. Anything that changes a URL on the docs needs a corresponding change in the Arctos handler - we may need to revise who has access to the Arctos docs, and that should be in the documentation-documentation, which is itself broken - I can find only http://handbook.arctosdb.org/documentation/documentation.html which just links to a bunch of 404s.

Related, the Arctos help tab links to https://arctosdb.org/, which isn't obviously helpful to operators. I think we should point the about/help tab to http://handbook.arctosdb.org/, or split "about" and "help", or add a prominent link to the handbook (eg, in the green bar), or SOMETHING to make the "how to do stuff" bits more obvious to users coming from Arctos.

**Comment by mkoo** [comment]
Closing issue since original issue is fixed with SSL cert implementation. Start a new issue please if broken links comes up again but https should be good to go

**Comment by campmlc** [comment]
I still get a warning that connection is not secure when trying to access arctos.database.museum from Firefox. 

Also, Arctos as Ecosystem link is still broken?

**Comment by mkoo** [comment]
HI Mariel, fixed the errant widget link on arctosdb.org but we (probably
Dusty and I) still have to coordinate with campus on the HTTPS business. It
took a long time to get .MUSEUM to fix something on their end. They sent
Dusty (our tech contact) credentials but I still dont see our info updated.
I'll email Dusty and campus separately to see if we can get that resolved.
Meanwhile, tell FF to go ahead wtih the unsecure site!
thanks, MK

**Comment by dustymc** [comment]
>They sent Dusty (our tech contact) credentials 

Nope. Last message I have was the 24th, you asking them again to send me something.

**Comment by mkoo** [comment]
SSL cert was implemented March 19th and with no more issues, I'm closing-yay!

**Comment by dustymc** [comment]
Reopening; handbook.arctosdb is still not securely configured which makes tight integration with arctos itself problematic.

<img width="798" alt="screen shot 2017-05-31 at 8 29 45 am" src="https://cloud.githubusercontent.com/assets/5720791/26640030/55bc2e7e-45db-11e7-98f0-dc434d9ddf2b.png">

**Comment by mkoo** [comment]
alrighty, I updated links to arctos.database.museum to https that I could
find.
any specific examples that need work?

**Comment by dustymc** [comment]
>links to arctos.database.museum to https

That is a Really Bad Idea at the moment; some browsers will block critical components. I'll have a fix out soon, I hope, but it's not there yet.

> specific examples that need work

https://handbook.arctosdb.org/

**Comment by dustymc** [comment]
https://arctos.database.museum should now be fully functional. (Turns out we had to register the https URL with Google's APIs.) Please test and comment on #1149 if you find any problems,

**Comment by dustymc** [comment]
Just checking in - https://handbook.arctosdb.org/ still returns
```
The owner of handbook.arctosdb.org has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website.
```

**Comment by ccicero** [comment]
Revisiting this. I just clicked on that handbook link and got:

Your connection is not private

Attackers might be trying to steal your information from handbook.arctosdb.org (for example, passwords, messages, or credit cards). NET::ERR_CERT_COMMON_NAME_INVALID

**Comment by dustymc** [comment]
This is still broken....

**Comment by dustymc** [comment]
why is this reopened?
