### ISSUE TITLE
Multi page media in a project - need to see media description

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1643]
**Describe the bug**
Multi page documents need more space in the project media section

**To Reproduce**
http://arctos.database.museum/project/arthur-h-harris-field-catalogs

**Expected behavior**
We need to be able to see the document description beneath the thumbnail in the project view.

**Screenshots**
![image](https://user-images.githubusercontent.com/5725767/43867754-bf9d8c78-9b27-11e8-8077-5ede7f9bbbeb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Forefox
 - Version 61.0.1

**Additional context**

**Comment by Jegelewicz** [comment]
> Do you want to see more text on all of the thumbs, or just make the first two (which don't seem to be sizing properly) look like the rest?

Just need enough text so that you can see what the media are.
http://arctos.database.museum/MediaSearch.cfm?offset=20&action=search&project_id=10002900
Lists them as separate pages and not in any kind of logical order (from the standpoint of a human). If that would list them in order by their Title/Page or description, then it would be more useful. If they can be sized so that we at least can see the description like the other files, that would help (but not sure if it would also fix the order of presentation issue).

**Comment by dustymc** [comment]
I shrunk the MPD thumb.

FWIW, MPDs were (in part) created to act like books, where you can just link to the object instead of to a "page." I think you're linking to the pages as they're assembled in the book, and also copies of them not assembled as the book, and maybe some other stuff. It's an overwhelming amount of linked stuff, maybe just because the preview images all look about the same.

> logical order

I'm up for ideas. 99+++% of everything that ever goes through that form won't have a title or page. Maybe 20% has a description. Multi-facet sort is expensive, this form is expensive, we're resource-limited. https://github.com/ArctosDB/arctos/issues/857 - if ya'll can give me more power, I'll use it for good..

**Comment by Jegelewicz** [comment]
> I'm up for ideas. 99+++% of everything that ever goes through that form won't have a title or page. Maybe 20% has a description. Multi-facet sort is expensive, this form is expensive, we're resource-limited. #857 - if ya'll can give me more power, I'll use it for good..

Would sorting by file name be too resource intensive? My files are named so that they should sort somewhat logically. Probably not perfect, but better that the random way things show up now....

**Comment by Jegelewicz** [comment]
Also, why do some MPD's show up in view with no problem, and some just spin forever?

![image](https://user-images.githubusercontent.com/5725767/44041620-752096f6-9edb-11e8-9476-34adb2a9ab7b.png)

This is a two page document and I just can't get the details to show.

**Comment by dustymc** [comment]
>sorting by file name

I think no problem - it's the IF... then... ELSE... something bla bla etc. stuff in the SORT that gets expensive (Oracle generally never figures out indexes for that, has to rifle through everything manually).

>some just spin forever

How'd you get there/where are you?

**Comment by Jegelewicz** [comment]
![image](https://user-images.githubusercontent.com/5725767/44042476-9dfc22e6-9edd-11e8-9d1c-bfbd3f81a685.png)

**Comment by dustymc** [comment]
Thanks. It's not happy with multiple created by agent relationships. Do we need to deal with that, or enforce a single one in the UI?

**Comment by Jegelewicz** [comment]
Oh - mine get put on there when I load the media - is there an easy way to get rid of me as a "created by" or do I need to go one by one and remove me?

**Comment by dustymc** [comment]
Should I remover you from these?

```

UAM@ARCTOS> select distinct a.media_id from media_relations a, media_relations b where a.media_id=b.media_id and a.media_relationship='created by agent' and b.media_relationship='created by agent' and a.related_primary_key=21300608 and b.related_primary_key=1008959;

  MEDIA_ID
----------
  10584470
  10584495
  10584472
  10584707
  10584485
  10584488
  10584632
  10584819
  10584476
  10584555
  10584712
  10584821
  10584492
  10584493
  10584479
  10584817
  10584820
  10584480
  10584556
  10584710
  10584818
  10584484
  10584471
  10584717
  10576765
  10584559
  10584634
  10584490
  10584473
  10584481
  10584482
  10584633
  10584713
  10584815
  10584491
  10584494
  10584711
  10584714
  10584554
  10584478
  10584486
  10584475
  10584489
  10584483
  10584635
  10584557
  10584474
  10584558
  10584487
  10584816
  10584708
  10584716
  10584477

53 rows selected.
```

**Comment by Jegelewicz** [comment]
As long as they all have Arthur H. Harris as the second created by agent, then yes!

**Comment by dustymc** [comment]
done

**Comment by Jegelewicz** [comment]
Great! That works much better now! But we are still getting this on the project page:
![image](https://user-images.githubusercontent.com/5725767/44050452-3094ffea-9ef4-11e8-89f4-435a2040fcf7.png)
So you can't see the descriptions there.

**Comment by Jegelewicz** [comment]
Dr. Harris says it works much better now, but:

> when looking at the detail pages, 1961 and 1971 don't show contents (just keep grinding away); however, clicking  in the left column brings up the page by page images.

When I looked up the 1961 AH Harris Catalog I got this:
![image](https://user-images.githubusercontent.com/5725767/44059700-7c9e2194-9f0f-11e8-84ef-06d5a6aef059.png)
The MPD shows up twice! Any idea why this would be? Same thing happens for 1971 AH Harris Catalog

**Comment by dustymc** [comment]
They'll be resized in next release.

You have a few pages licensed differently, which causes duplication.

```

UAM@ARCTOS> select MEDIA_LICENSE_ID, media_id from media where media_id in (select media_id from media_labels where MEDIA_LABEL='title' and LABEL_VALUE in ('1961 AH Harris Catalog','1971 AH Harris Catalog')) order by MEDIA_LICENSE_ID;

MEDIA_LICENSE_ID   MEDIA_ID
---------------- ----------
	       2   10584565
	       2   10584566
	       2   10584604
	       2   10584595
	       2   10584593
	       2   10584592
	       2   10584591
	       2   10584590
	       2   10584589
	       2   10584588
	       2   10584587
	       2   10584586
	       2   10584585
	       2   10584584
	       2   10584583
	       2   10584567
	       2   10584568
	       2   10584569
	       2   10584570
	       2   10584571
	       2   10584572
	       2   10584573
	       2   10584574
	       2   10584575
	       2   10584576
	       2   10584577
	       2   10584578
	       2   10584579
	       2   10584581
	       2   10584582
		   10584607
		   10584603
		   10584602
		   10584601
		   10584600
		   10584599
		   10584608
		   10584597
		   10584596
		   10584606
		   10584594
		   10584605
		   10584580
		   10584598

44 rows selected.

```

**Comment by Jegelewicz** [comment]
Check - I'll get those fixed! Thanks!

**Comment by Jegelewicz** [comment]
BTW - I have no way of finding those media with that list of numbers....at least no way that I know of.

**Comment by dustymc** [comment]
Yea, I don't think you can find them as a list - the results page will compress them into the two MPDs (that's the point of MPDs!). I think you'll have to update them individually, or let me know what you want and I can SQL it.

**Comment by Jegelewicz** [comment]
I think I got them all just going page-by-page.

**Comment by dustymc** [comment]
>I think I got them all 

Yep, looks like it.
