### ISSUE TITLE
Media Upload Error

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1978]
I am using the media upload batch tool and I uploaded several batches a week ago, none of them have completed yet. When I view the splash page, one has this remark:

![image](https://user-images.githubusercontent.com/5725767/54491626-80302580-4885-11e9-87c0-afc0dbac46ce.png)

If I scroll down to the details for it, almost all of the stuff has loaded, but about a dozen or so records are still in the "previewed" status.

I think this may have caused the upload tool to stick and I'm not sure the best way to proceed or what caused the problem (maybe trying to load too many images?). Let me know how to proceed.

**Comment by dustymc** [comment]
Can you send me the zip? I can see that something isn't happy, but I'm not sure what.

**Comment by dustymc** [comment]
Elevating priority and shutting this down for now - the errors are plugging up everything.

**Comment by Jegelewicz** [comment]
![image](https://user-images.githubusercontent.com/5725767/54549311-6bc85780-496f-11e9-8861-f40593b594fe.png)

That's probably it. I can split the images into two files and try again whenever it's back up...

**Comment by dustymc** [comment]
I should have it back up today. Letting me load one of your ZIPs would still be useful. You can email it to data.5xret59ahx21x7na@u.box.com and let me know when it's there. If there are size limitations I can at least try to be explicit about them.

The SCP pathway exists as well, and has no size limits that you're likely to encounter.

**Comment by Jegelewicz** [comment]
Ok, will email as they are all too big for GitHub

**Comment by dustymc** [comment]
I think it's all back up. It will take it a while to error out everything that didn't work. If you want to try again with smaller files you can. I'd prefer to wait for a test box to try your huge files, but I'm OK with doing that at prod too. Let me know....

**Comment by Jegelewicz** [comment]
I'll wait until tomorrow, split stuff up and try again.

**Comment by Jegelewicz** [comment]
I uploaded one batch and it seems to be just sitting there.
![image](https://user-images.githubusercontent.com/5725767/54764137-cc000900-4bbc-11e9-888a-234deadf4bea.png)

**Comment by dustymc** [comment]
Woops! Should be doing something now.

**Comment by Jegelewicz** [comment]
Still seems stuck

![image](https://user-images.githubusercontent.com/5725767/54931299-578bd980-4ede-11e9-9760-48f2a730adb3.png)

**Comment by dustymc** [comment]
Is this still a problem? I still do not have problematic data.

**Comment by Jegelewicz** [comment]
Nothing has loaded from the one file I uploaded several weeks ago...see above.

**Comment by dustymc** [comment]
Please send me your ZIP.

**Comment by Jegelewicz** [comment]
Emailing it.

**Comment by dustymc** [comment]
I think the job is happy again, although I had to throttle it heavily so it's going to be slower in the future.

Here's the CSV.

[media_bulk_zip190858331.csv.zip](https://github.com/ArctosDB/arctos/files/3041040/media_bulk_zip190858331.csv.zip)

**Comment by Jegelewicz** [comment]
Was it the size of th

**Comment by Jegelewicz** [comment]
This is still not working.

![image](https://user-images.githubusercontent.com/5725767/56736574-bb93fe80-6725-11e9-8405-066e9a158615.png)

What do we need to figure it out?

**Comment by dustymc** [comment]
Yes the pre-April jobs are not going to complete. I can delete them if there's nothing you need.

**Comment by Jegelewicz** [comment]
go ahead and delete them and I'll try again. Thanks!

**Comment by dustymc** [comment]
done

**Comment by Jegelewicz** [comment]
This is still not functioning - been as "renamed" for days.http://arctos.database.museum/tools/uploadMedia.cfm?action=preview

**Comment by dustymc** [comment]
Send me your ZIP - I may have it throttled enough that it's deleting stuff before it can unroll it....

**Comment by Jegelewicz** [comment]
will email

**Comment by dustymc** [comment]
It's taking ~30s to create a single preview from the 1M files. I've throttled to accommodate that and will continue monitoring. I think that's going to work, at least for this particular batch, but it's going to slow the process further.

I think we're at another chokepoint in https://github.com/ArctosDB/arctos/issues/1446. We have a good "media server" but now we're bouncing off the limits of using the webserver to process media. We should probably start looking for a way to avoid that (can TACC automate more in the SCP pathway?) or offload it to a server running more appropriate software (whatever that is...).

**Comment by dustymc** [comment]
The process completed without intervention, so hopefully it'll limp along a while longer. 

Here's your bulkloader file.

[media_bulk_zip195317079.csv.zip](https://github.com/ArctosDB/arctos/files/3142778/media_bulk_zip195317079.csv.zip)

Leaving this open - a second not-quite-web-server for some alternate to CFIMAGE, potentially running scheduled tasks, etc. would be very useful; how do we do that?

**Comment by Jegelewicz** [comment]
> a second not-quite-web-server for some alternate to CFIMAGE, potentially running scheduled tasks, etc. would be very useful; how do we do that?

Rhetorical question? Does this just involve funds or something else?

**Comment by dustymc** [comment]
Yea sorta - more "note to self" but probably requires funds IF we go that way. The only thing I'm really sure of is that I don't currently have the most efficient tools to manipulate images. Ideally it would start with someone who knows a lot more about image manipulation than I do.

**Comment by dustymc** [comment]
>don't currently have the most efficient tools to manipulate images

I reduced the preview quality; things are (sometimes?!) running again, but it's still very inefficient.

**Comment by Jegelewicz** [comment]
I've been trying to bulkload the metadata from above and keep getting the error "missing comma". Can you tell me what's causing that?

[meloid beetles media bulkload.zip](https://github.com/ArctosDB/arctos/files/3259403/meloid.beetles.media.bulkload.zip)

**Comment by dustymc** [comment]
>missing comma

MEDIA:RELATIONSHIP:2
