### ISSUE TITLE
Error using scary red box barcode swapper

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3210]
Help please - Error and file below:

An error occurred while processing this page!Message: ERROR: operator does not exist: character varying = bigint Hint: No operator matches the given name and argument types. You might need to add explicit type casts. Position: 154Detail:Check the Arctos Handbook for more information on errors.This message has been logged as FF95C209-6A10-4338-835FCF48769623D9 Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue.
[DGR10641-F4-R5-B4.zip](https://github.com/ArctosDB/arctos/files/5533138/DGR10641-F4-R5-B4.zip)

--

**Comment by campmlc** [comment]
May have found it - problem with label

**Comment by campmlc** [comment]
Still doesn't work. 
New error:
An error occurred while processing this page!
Message: Error invoking external process
Detail: psql:/usr/local/webroot/temp/excopy_campmlc_20201112021130165_959.sql:1: ERROR: syntax error at or near "labe" LINE 1: ...emp_scaryswapper (box_barcode,position,receiving_ labe l,don... ^
Check the Arctos Handbook for more information on errors.

[DGR10641-F4-R5-B4 (2).zip](https://github.com/ArctosDB/arctos/files/5533164/DGR10641-F4-R5-B4.2.zip)

**Comment by dustymc** [comment]
<img width="169" alt="Screen Shot 2020-11-12 at 12 53 25 PM" src="https://user-images.githubusercontent.com/5720791/98995354-121e8480-24e6-11eb-8bf5-f636d581d1d9.png">


<img width="163" alt="Screen Shot 2020-11-12 at 12 53 06 PM" src="https://user-images.githubusercontent.com/5720791/98995339-092db300-24e6-11eb-9abd-1341290c26c5.png">

**Comment by campmlc** [comment]
Fixed label header problem. Now I get this error:
An error occurred while processing this page!
Message: ERROR: operator does not exist: character varying = bigint Hint: No operator matches the given name and argument types. You might need to add explicit type casts. Position: 154
Detail:
Check the Arctos Handbook for more information on errors.
This message has been logged as 4EF36A21-A0CA-4E07-968FF94EECF842BF Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue.

**Comment by dustymc** [comment]
Should be patched

**Comment by hhumphrey13** [comment]
Hi, I'm working with @campmlc on this, and we are still getting an error when trying to upload: "500 Internal Server Error".

My data is attached. Thanks!
[DGR11_R5_B1.csv.zip](https://github.com/ArctosDB/arctos/files/5539494/DGR11_R5_B1.csv.zip)

**Comment by campmlc** [comment]
Moving this to high priority - it is actively impeding daily work. Help please?

**Comment by dustymc** [comment]
Please set milestones - I filter on them. https://handbook.arctosdb.org/how_to/How-to-organize-Issues.html

I rewrote a query for PG, then rebuilt some CF code because lucee inexplicably chokes on the work "position." Should be functional and patched, but please very carefully check to make sure I didn't bork something. You can start over or jump in at https://arctos.database.museum/tools/scaryBarcodeSwapper_box.cfm?action=verify. Nothing has been tested past that step - I'll need clean data if it doesn't just work, which it hopefully will.

**Comment by campmlc** [comment]
Thanks, will do!

**Comment by hhumphrey13** [comment]
I believe it worked! It loads then says, "fail; check data and reload". It has a status row, and one cell says donor_not_found, but I suspect that's something on our end.

Thanks for the patch, @dustymc !

**Comment by campmlc** [comment]
I'm still getting this error: An error occurred while processing this page!
Message: Error invoking external process
Detail: psql:/usr/local/webroot/temp/excopy_campmlc_20201118111146531_533.sql:1: ERROR: syntax error at or near "44323" LINE 1: copy cf_temp_scaryswapper (nk 44323 hk,nk 44323 l,nk 44324 h... ^

I've searched on the labels "NK 44323 HK" and they exist. Not sure what syntax error it is finding.
File is attached.
[DGR10641-F4-R5-B4_labels.zip](https://github.com/ArctosDB/arctos/files/5564584/DGR10641-F4-R5-B4_labels.zip)

**Comment by dustymc** [comment]
The csv is a mess

**Comment by campmlc** [comment]
I don't have tools to see the problem. Opening in text editor shows nothing
wrong. Can you clarify?

**Comment by dustymc** [comment]
>Can you clarify?

Apparently not! The CSV you attached works fine; I don't think it could have produced that error, or I need clarification on what you're doing.

**Comment by campmlc** [comment]
Let me try another similar file.

**Comment by campmlc** [comment]
Tried that one again and this morning it loaded, but I got this, apparently
from a terminal space.
fail; check data and reload
DGR10641 [tree]
<https://arctos.database.museum/findContainer.cfm?container_id=18451827>
[edit]
<https://arctos.database.museum/EditContainer.cfm?container_id=18451827> 67
[tree]
<https://arctos.database.museum/findContainer.cfm?container_id=18451954>
[edit]
<https://arctos.database.museum/EditContainer.cfm?container_id=18451954> NK
44353 Z� [tree]
<https://arctos.database.museum/findContainer.cfm?container_id=> [edit]
<https://arctos.database.museum/EditContainer.cfm?container_id=> A9IO8
[tree]
<https://arctos.database.museum/findContainer.cfm?container_id=19702674>
[edit]
<https://arctos.database.museum/EditContainer.cfm?container_id=19702674>
tube_not_foundFixed that, and it loaded fine! Not sure what was up last
night. I did not change the file between last night and this morning.
Thanks!
