### ISSUE TITLE
Request - sort by catalog number not by alphanumeric (GUID)

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#3343]
I dont see this issue listed but I heard it a few times in only the last month!

In search result table, sort by numeric catalog number even if it's being displayed as the alphanumeric GUID. See attached which shows the first 19 records of LINGU where it starts as LINGU:HERP:1, LINGU:HERP:10, LINGU:HERP:11, etc instead of LINGU:HERP:1, LINGU:HERP:2, LINGU:HERP:3 (sorry to being picking on LINGU but applies to any search)

Seems that there may be both a SQL way to do this or something to do with the form  such as sort by catalogNumber but display the tripart alphanumeric to achieve the same ends.

would be high value display feature for all arctos users!

![Firefox_Screenshot_2021-01-09T06-28-26 811Z](https://user-images.githubusercontent.com/2523089/104108364-c8011780-5278-11eb-8d1f-dccfaab30811.png)

**Comment by AJLinn** [comment]
We use leading zeros to make sure all numbers sort properly (e.g., UAM:EH:UA2020-001-0001). However, we do run into trouble with our pre-2000 numbers that are represented by 2 places in the UA-string (e.g., UA64-021-0001) instead of the UA64 number sorting first, the UA2020 number will preceed it. Haven't figured out a way to make that work yet...

**Comment by campmlc** [comment]
Agree. I have to download to excel and parse the column to do this now.

**Comment by mkoo** [comment]
that's what I would hope to fix-- necessitating leading 0's which can cause its own problems and manually sorting in a separate app. probably other annoyances /issues may be addressed too with this fix!

**Comment by dustymc** [comment]
Catnum isn't numeric, and I don't see any way to fake it. We could add cat_num_integer to FLAT, which would provide a numeric sort for collections that use that.

**Comment by Jegelewicz** [comment]
> We could add cat_num_integer to FLAT, which would provide a numeric sort for collections that use that.

This is long overdue. I say we get it done now.

**Comment by KyndallH** [comment]
Beyond catnum, I run into this issue other places and it is frustrating. 

![Screen Shot 2021-01-14 at 11 26 45 AM](https://user-images.githubusercontent.com/16887896/104645357-69aead00-565b-11eb-838f-3be1ff1e9141.png)

**Comment by KyndallH** [comment]
![Screen Shot 2021-01-14 at 11 28 41 AM](https://user-images.githubusercontent.com/16887896/104645520-9cf13c00-565b-11eb-97d5-5445c97b49d1.png)

**Comment by campmlc** [comment]
Yes! I second @KyndallH .  We need options to select how we want containers and hierarchies to be sorted and displayed.

**Comment by itzuecs** [comment]
Hello,

I just want to follow up with this issue. We are facing the same sorting problem. Is there any update about @dustymc suggestion? Thanks!

> Catnum isn't numeric, and I don't see any way to fake it. We could add cat_num_integer to FLAT, which would provide a numeric sort for collections that use that.

**Comment by Jegelewicz** [comment]
> Catnum isn't numeric, and I don't see any way to fake it. We could add cat_num_integer to FLAT, which would provide a numeric sort for collections that use that.

@dustymc if this wouldn't be too difficult, I think we should do it. This has been a long-standing complaint.

**Comment by dustymc** [comment]
Blocked by https://github.com/ArctosDB/arctos/issues/2154

**Comment by dustymc** [comment]
Done

**Comment by itzuecs** [comment]
I am not sure how this fix the issue #3334 Request - sort by catalog number not by alphanumeric (GUID). The numbers in our catalogue are still not in order on Arctos. Do you mind explaining how this will help with the ordering to collections that do not need the new_new_catnum?

**Comment by dustymc** [comment]
<img width="354" alt="Screen Shot 2021-04-08 at 6 41 42 AM" src="https://user-images.githubusercontent.com/5720791/114037211-9e369d00-9835-11eb-95ab-610ae2723042.png">
<img width="200" alt="Screen Shot 2021-04-08 at 6 41 51 AM" src="https://user-images.githubusercontent.com/5720791/114037223-a1318d80-9835-11eb-9e32-bd18b0447c82.png">
<img width="261" alt="Screen Shot 2021-04-08 at 6 42 24 AM" src="https://user-images.githubusercontent.com/5720791/114037236-a42c7e00-9835-11eb-91cf-8a221baa5cc7.png">

**Comment by dustymc** [comment]
@mkoo @itzuecs can this be closed?

**Comment by KyndallH** [comment]
What about Next2layers? See my comment above? Or should that be a different issue?

**Comment by dustymc** [comment]
>Or should that be a different issue?

Yes please.

**Comment by itzuecs** [comment]
> @mkoo @itzuecs can this be closed?

Yes, thanks!
