### ISSUE TITLE
Code Table Request - add 'preps unfinished' to accn status

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#5375]
**Goal**
To make it easier to use Arctos to track the status of different accessions.

**Context**
-- Accession_status currently has the following values: 'in process' 'ready to catalog' 'complete'. 
-- 'ready to catalog' and 'complete' are self explanatory, but 'in process' can mean lots of different things - e.g., in process of acquisition, in process of preparation, OR in process of cataloging.
-- We currently use Google docs to track accessions where specimens are not fully prepared. Either they're in a freezer or they're in process of preparation. It will greatly streamline curatorial workflow if we can use Arctos for that purpose. We do not catalog items in an accession until everything for that accession has been prepared, so we  need to know which accessions have unfinished preps. Once all preps are done, then the accession is 'ready to catalog'

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctaccn_status

**Proposed Value**
'preps unfinished'

**Proposed Definition**
Preparations have not be completed for this accession. Items may either be in a freezer or other container awaiting preparation, or they may be in various stages of preparation.'

**Comment by dustymc** [comment]
I don't think there's anything functional about those values (in the code, they're clearly functional to humans), this isn't a different way of saying something else - goferit.

``in process`` could probably be clarified at the same time, but I'm not sure what to suggest. "General-puurpose status of not being complete'??

**Comment by ewommack** [comment]
> this isn't a different way of saying something else - goferit

I agree with Dusty here. 
"Preps unfinished" seems like a subsection of "In Process" though. Would it be more usable for multiple types of collections to create subsets of "In Process"?
"In Process of acquisition"
"In Process of preparation"
"In Process of cataloging"
"In Process of installation"

**Comment by campmlc** [comment]
I like @ewommack 's suggestion.

**Comment by ccicero** [comment]
I like that too! However, how do we migrate the ones currently 'in process' to one of those options? Can we add those values to the CT but we probably also need to keep 'in process' or change it to something generic ???

**Comment by dustymc** [comment]
>how do we migrate the ones currently 'in process' to one of those options

You can't, and the documentation should make it clear that plain ol' ``in process`` is outside of any more-specific path/workflow/status; it encompasses all of the more-specific states, however vaguely.

Also lose the Proper Case please - "in process of acquisition" etc.

**Comment by ccicero** [comment]
+1

**Comment by ewommack** [comment]
> Also lose the Proper Case please - "in process of acquisition" etc.

"in process"
"in process of acquisition"
"in process of preparation"
"in process of cataloging"
"in process of installation"
@dustymc - better?

Since I was trying to think of all collections types @AJLinn @Nicole-Ridgwell-NMMNHS - anything else you guys have for processing?

**Comment by ccicero** [comment]
Draft definitions (I used 'components' per our CT discussion 12/15/2022, but that's negotiable although it would be good to use consistent terminology):

-- in process - "This accession is a work in progress, but its exact status is unknown."  (slightly expanded from current)
-- in process of acquisition - "Steps have been taken to acquire this accession, but not all components and/or documentation are in hand. Example: Components are accessioned but the collection is still waiting on more items or on data, permits, or other documentation."
-- in process of preparation - "Preparation of components pertaining to this accession is incomplete. Components may be in a freezer awaiting preparation or they may be in various stages of preparation (e.g., specimen is skinned but not stuffed)."
-- in process of cataloging - "Components pertaining to this accession are in the process of being assigned catalog numbers or of being labeled or numbered. This status typically precedes installation."
-- in process of installation - "Components pertaining to this accession are in the process of being moved to where they belong in the collection."
ready to catalog- "All components pertaining to this accession are ready to be assigned catalog numbers." (slightly modified from current)
complete - "All components and information pertaining to the accession are where they belong. Components have been installed into the collection." (slightly modified from current)

**Comment by Jegelewicz** [comment]
Term | definition 
 -- | -- 
in process | This accession is a work in progress, but its exact status is unknown. Use more specific statuses if possible.
in process of acquisition | Steps have been taken to acquire this accession, but not all components and/or documentation are in hand. Example: Components are accessioned but the collection is still waiting on more items or on data, permits, or other documentation.
ready for preparation | All components pertaining to this accession are ready for preparation.
in process of preparation | Preparation of components pertaining to this accession is incomplete. Example: Components may be in a freezer awaiting preparation or they may be in various stages of preparation (e.g., specimen is skinned but not stuffed).
ready to catalog | All components pertaining to this accession are ready to be assigned catalog numbers and labeld.
in process of cataloging | Components pertaining to this accession are in the process of being assigned catalog numbers or of being labeled or numbered. This status typically precedes installation.
ready to install | All components pertaining to this accession are ready to be  moved to where they belong in the collection.
in process of installation | Components pertaining to this accession are in the process of being moved to where they belong in the collection.
complete | All components and information pertaining to the accession are where they belong. Components have been installed into the collection.

**Comment by ccicero** [comment]
I think we can merge 'ready for preparation' and 'in process of preparation' and tweak the definition - basically, are all the items prepared or not? I suggest combining into something that's a version of what I originally suggested:

preparation incomplete - "All components pertaining to this accession are ready for preparation but preparation is not completed. Components may be in a freezer awaiting preparation or they may be in various stages of preparation (e.g., specimen is skinned but not stuffed)." (I actually like that better than 'in process of preparation' because carcasses sitting in a freezer are not in process)

The rest looks good to me, and I think will be super helpful.

I'm also thinking it would be useful to have these terms ordered (in the dropdown) sequentially in terms of steps in the process versus alphabetically. @dustymc is that feasible? 

in process of acquisition
preparation incomplete
ready to catalog
in process of cataloging
ready to install
in process of installation
complete

**Comment by dustymc** [comment]
>ordered (in the dropdown) sequentially 

It's not magic but it would mean one thing's different than all the rest, and that'll eventually find a way to be weird. Any reason not to prefix with numbers/letters so they'll sort natively?

**Comment by ccicero** [comment]
No reason not to prefix with a number. Will others find that useful and more sensical than alphabetical which would look like:

complete
in process of acquisition
in process of cataloging
in process of installation
preparation incomplete
ready to catalog
ready to install

NEW TERMS IN ORDER:
1-in process of acquisition
2-preparation incomplete
3-ready to catalog
4-in process of cataloging
5-ready to install
6-in process of installation
7-complete

**Comment by Jegelewicz** [comment]
Term | definition 
 -- | -- 
in process | This accession is a work in progress, but its exact status is unknown. Use more specific statuses if possible.
1-in process of acquisition | Steps have been taken to acquire this accession, but not all components and/or documentation are in hand. Example: Components are accessioned but the collection is still waiting on more items or on data, permits, or other documentation.
2-preparation incomplete | All components pertaining to this accession are ready for preparation but preparation is not completed. Components may be in a freezer awaiting preparation or they may be in various stages of preparation. Example: specimen is skinned but not stuffed.
3-ready to catalog | All components pertaining to this accession are ready to be assigned catalog numbers and labeled.
4-in process of cataloging | Components pertaining to this accession are in the process of being assigned catalog numbers or of being labeled or numbered. This status typically precedes installation.
5-ready to install | All components pertaining to this accession are ready to be  moved to where they belong in the collection.
6-in process of installation | Components pertaining to this accession are in the process of being moved to where they belong in the collection.
7-complete | All components and information pertaining to the accession are where they belong. Components have been installed into the collection.

**Comment by campmlc** [comment]
I like this - except not everyone will follow the same order of steps? But
that shouldn't matter - I can complete 4 and then go back to 2.

**Comment by wellerjes** [comment]
Thoughts on changing "install" to "integrate"? When I hear "install" or "installation", I think of installing it in an exhibit, not putting it away in our collections.

**Comment by ewommack** [comment]
> When I hear "install" or "installation", I think of installing it in an exhibit, not putting it away in our collections.

Can you do both for an accession? The definition is pretty broad, and wouldn't some accessions go from prep into an exhibit or into the cases depending on their intended use?

**Comment by ccicero** [comment]
+1 to what @ewommack wrote. 'Install' can mean both things, so I think we just need to update the definition. When I hear 'integrate' I don't think of putting something away in the collection (for example, specimens from one accession are received at different times; each time material is received, it's integrated with the rest of that accession but not yet cataloged) 

Suggested updates:

5-ready to install: All components pertaining to this accession are ready to be moved to where they belong in the collection or  exhibit.

6-in process of installation: Components pertaining to this accession are in the process of being moved to where they belong in the collection or exhibit.

**Comment by ccicero** [comment]
Can we finalize these additions to the CT and their definitions? I'd like to start using this asap.

**Comment by jldunnum** [comment]
When I look through the various stages I think we would probably only be able use "in process" and "complete".  Once we have acquired an accession we don't process the whole accession in complete steps. For example, we may digitally catalog the entire accession first, then prepare and install some subset before doing anything with the rest of the specimens. Basically we could have parts of an accession at every level of the process. 
In regard to number 1 - would you assign an accession number before you've fully acquired it? I think of accessioning as the act of taking legal responsibility for the collection or object in question.  We wouldn't do that if it didn't have all the proper documentation ahead of time.

**Comment by ccicero** [comment]
@jldunnum I think this system will allow different collections to use whatever steps make sense for them in tracking accession status. We don't catalog bird accessions until all specimens have been fully prepped, but other collections may do something similar to what you do.

I could see using #1 for (e.g.) archival or observational accessions where permits are not the issue. Sometimes we acquire archival accessions - e.g., field notes - in stages and keep the accession open. Likewise, we may accession a set of observational records while we're still waiting on some information. There are also cases where we will accession a set of specimens but still need some documentation (although that's less common).

**Comment by jldunnum** [comment]
Ok, not an issue if other collections will use them

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Jegelewicz** [comment]
I have some concerns about the numbering which is MVZ's workflow, but not necessarily everyone else's. I suggest that the order of completion should come from a workflow held by the institution. This can be recorded in Github (see what @Nicole-Ridgwell-NMMNHS is doing with cabinet inventories and place creation - https://github.com/ArctosDB/Arctos-Workflows/issues). I suggest the terms be added as follows:

Term | definition 
 -- | -- 
in process | This accession is a work in progress, but its exact status is unknown. Use more specific statuses if possible.
in process of acquisition | Steps have been taken to acquire this accession, but not all components and/or documentation are in hand. Example: Components are accessioned but the collection is still waiting on more items or on data, permits, or other documentation.
preparation incomplete | All components pertaining to this accession are ready for preparation but preparation is not completed. Components may be in a freezer awaiting preparation or they may be in various stages of preparation. Example: specimen is skinned but not stuffed.
ready to catalog | All components pertaining to this accession are ready to be assigned catalog numbers and labeled.
in process of cataloging | Components pertaining to this accession are in the process of being assigned catalog numbers or of being labeled or numbered. This status typically precedes installation.
ready to install | All components pertaining to this accession are ready to be  moved to where they belong in the collection.
in process of installation | Components pertaining to this accession are in the process of being moved to where they belong in the collection.
complete | All components and information pertaining to the accession are where they belong. Components have been installed into the collection.

**Comment by ccicero** [comment]
I'm fine removing the numbers but other than that, what is different here? If we enter them without numbers, they'll just sort alphabetically - correct? That's fine with me, order is less important than having the different options for status.

Can we move forward with this?

**Comment by Jegelewicz** [comment]
> If we enter them without numbers, they'll just sort alphabetically - correct?

Yep

> Can we move forward with this?

No objection from me.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I think this is great! I just have one small suggested change for the preparation definition:

All components pertaining to this accession are ready for preparation but preparation is not completed. Components may be in a freezer **or field jacket** awaiting preparation or they may be in various stages of preparation. Example: Specimen is skinned but not stuffed.

**Comment by Jegelewicz** [comment]
Added above to https://github.com/ArctosDB/arctos/issues/5375#issuecomment-1361466591

**Comment by ewommack** [comment]
Looks good to me.

I now want stickers for when I finish different stages....

**Comment by ccicero** [comment]
@dustymc I'm working on adding these terms but am running into a 20 character limit. Can you please increase the character limit (30 characters)? Thanks.

**Comment by ccicero** [comment]
@dustymc not sure if you saw this but can you fix it so I can add these values to the CT? Thanks!

**Comment by dustymc** [comment]
Done.

**Comment by ccicero** [comment]
@dustymc Did you make the change in test or prod? I'm still getting an error in prod:

ERROR_MESSAGE: value too long for type character varying(20) Where: SQL statement "insert into log_CTACCN_STATUS( username, change_date, n_ACCN_STATUS, n_DESCRIPTION, o_ACCN_STATUS, o_DESCRIPTION ) values ( session_user, LOCALTIMESTAMP, NEW.ACCN_STATUS, NEW.DESCRIPTION, OLD.ACCN_STATUS, OLD.DESCRIPTION )" PL/pgSQL function trigger_fct_tr_log_ctaccn_status() line 3 at SQL statement

ERROR_SQL: INSERT INTO ctaccn_status (accn_status ,description ) VALUES ('in process of acquisition' ,'Steps have been taken to acquire this accession, but not all components and/or documentation are in hand. Example: Components are accessioned but the collection is still waiting on more items or on data, permits, or other documentation.' )

**Comment by ccicero** [comment]
Worked, thanks! Values added to [ctaccn_status_](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctaccn_status).
