### ISSUE TITLE
BerkeleyMapper error from link in Locality record

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#5740]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Go to this locality record:
https://arctos.database.museum/editLocality.cfm?locality_id=11640502

click the link "Map it in BerkeleyMapper!" https://arctos.database.museum/bnhmMaps/bnhmPointMapper.cfm?locality_id=11640502

and get this error (and no map of the desired locality)

Unable to set session on server.  Ensure tabfile & configfile locations are accessible and that the tmp directory on server is writeable.

unable to set session on server, check temporary directory?

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
medium

**Comment by mkoo** [comment]
misconfig file going on here:
@jdeck @dustymc 

![Firefox_Screenshot_2023-03-02T03-51-49 254Z](https://user-images.githubusercontent.com/2523089/222326923-b67050df-e74e-4b00-924b-ff94ca7a93f8.png)

**Comment by dustymc** [comment]
thanks @mkoo - that's a poor choice/source for file name (contains /), fixed in next release.

@DerekSikes is may work after you log out/in, and I'll try to get a release with a fix out ~tonight.

**Comment by mkoo** [comment]
Back working after Friday's updates

**Comment by cjconroy** [comment]
I am still having a similar problem. I can pull up records on Berkeley Mapper. But, when I click on the icons to find the records the top of the screen flashes "loading records" in a yellow bar for a half a second, but then nothing. No table at the bottom of the screen. Is there something else I need to do on my computer?
