### ISSUE TITLE
Picked Locality Attributes remain in single-record data entry form after saving as a new record

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#6025]
Pick a locality or event and use without modification in the single record data entry form
Save the data  as new record.
If there were locality attributes in the event or locality, they remain in the data entry form. 
We have hundreds of these attributes since we converted to GADM and moved data from Higher Geography to Specific Locality

The attributes should be erased with all the other data except what is in the profile.

Screenshot
<img width="778" alt="Screenshot 2023-03-18 at 8 27 26 AM" src="https://user-images.githubusercontent.com/15368365/226112166-4fcec465-ceb4-4c47-834b-a78b1dde41b4.png">

This happens on PCs and on Mac with Chrome or Firefox

**Comment by dustymc** [comment]
This can be addressed as part of https://github.com/ArctosDB/arctos/issues/5193

**Comment by sharpphyl** [comment]
> This can be addressed as part of https://github.com/ArctosDB/arctos/issues/5193

I'm not sure how modifications to the bulkloading process would impact the single-record date entry screen, but as long as the bug is resolved, we're fine.

**Comment by sharpphyl** [comment]
Wait.  This is a carry-forward that shouldn't carry forward to the next screen.  Is that a bulkloader issue?

**Comment by dustymc** [comment]
Not really (and it's not really a "carry" it's just a display of what's on a picked event - still broken and confusing, but it's not replicating data) but that will require the screen to be rewritten, and what happens there - eg https://github.com/ArctosDB/arctos/issues/5193#issuecomment-1481969696 - might radically alter that screen. ("Picking a locality" is necessarily going to mean something else if you can pick several of them.)
