### ISSUE TITLE
search results: add "fields" to FLAT 

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6097]
**Is your feature request related to a problem? Please describe.**

https://github.com/ArctosDB/arctos/issues/6017 is causing pain for users and glitches in the system and I think cannot be ignored any longer even though the identifier discussions have stalled. I have to remove the many and mostly unused identifiers options from results ASAP in the name of stability.

I'd like to compensate by adding the things that are most used, and some loose ends that have been floating around. Here's what I think needs to happen, please let me know ASAP if anything else is regularly necessary in results.

* superorder (for @DerekSikes via https://github.com/ArctosDB/arctos/issues/6035)
* Preparator Number (see https://github.com/ArctosDB/arctos/issues/6031, I think this is stable)
* AF
* NK

above from https://github.com/ArctosDB/arctos/issues/5460 @jebrad did I miss anything?

**Describe what you're trying to accomplish** 

Cache whatever's necessary to make Arctos performant, without making any new messes.

**Describe the solution you'd like**

Input from anyone who wants to include stuff in search results. (Perhaps excepting Attributes, which is a bit of a monster and needs a dedicated discussion.)

**Describe alternatives you've considered**

Things that a few users occasionally need can be quickly added dynamically, and there are download options for most of this; not adding something here does not mean it's not available. 

**Additional context**

**Priority**

This is already smouldering, I'll make the changes and run the updates this weekend unless someone has a compelling reason not to.

Other things can be added at any time, but (depending on the specifics) it can take several days of CPU to complete; anything that can be done now should be done now for the sake of efficiency.

**Comment by Jegelewicz** [comment]
What "identifiers" will be included after the above are added?

**Comment by dustymc** [comment]
These are currently available (but may not be mapped to the UI, I'll make sure they are when this goes out):

* field number
* collector number
* GenBank
* Organism ID

**Comment by Jegelewicz** [comment]
Would it make sense to add 

- institutional catalog number
- other identifier

?

Those are going to get a lot of use once we make it through the more specific id types.

**Comment by Jegelewicz** [comment]
Fair - I just wanted to bring it up.

**Comment by dustymc** [comment]
Done. It will take ~an hour for the UI to refresh, and a few days for the cache to catch up.

**Comment by campmlc** [comment]
Search results still show nk as a column, as it is part of my customization, but no values are populating the field, even though NK shows up in the concatatenated identifiers field?

![Screenshot 2023-04-09 22 58 49](https://user-images.githubusercontent.com/14808196/230829247-7a7b8886-089b-4811-9d9a-78c2c7a604c8.png)

**Comment by campmlc** [comment]
@jldunnum @AdrienneRaniszewski are having the same problem. We urgently need to be able to download NK as a separate column. I thought this was not going to be affected by this issue. 
Priority: High

**Comment by Jegelewicz** [comment]
Doesn't work for me either.

![image](https://user-images.githubusercontent.com/5725767/231014082-1434b2f8-81b6-462b-b636-e3903a16c52f.png)

**Comment by Jegelewicz** [comment]
@campmlc perhaps it is this 

`a few days for the cache to catch up.`

**Comment by AdrienneRaniszewski** [comment]
The NK numbers still aren't populating in the search results. Which is making finding things pretty tricky and time consuming. This is being restored, correct?

**Comment by dustymc** [comment]
The cache got stuck and didn't properly wrap up last night, it should be clearing up now-ish.

**Comment by dustymc** [comment]
I believe that everything is now caught up.
