### ISSUE TITLE
missing records in search

### ISSUE THREAD

**Issue by jldunnum** [ArctosDB/arctos#6674]
These two Myospalax do not come up when I do a search on "Myospalax". Seems like something to do with the taxonomy field. I can get them by searching for everything from their locality though. Any thoughts?

https://arctos.database.museum/guid/MSB:Mamm:94336
https://arctos.database.museum/guid/MSB:Mamm:94335

**Comment by Jegelewicz** [comment]
@jldunnum where are you searching?

this finds them
![image](https://github.com/ArctosDB/arctos/assets/5725767/f709106a-7096-47c6-a012-31737d635fde)

**Comment by Jegelewicz** [comment]
so does this
![image](https://github.com/ArctosDB/arctos/assets/5725767/23a89014-4170-45b0-a972-3c171dd891aa)

**Comment by jldunnum** [comment]
Searching in genus.
Also missing these two. They are all from the 1999 expedition.
https://arctos.database.museum/guid/MSB:Mamm:94333
https://arctos.database.museum/guid/MSB:Mamm:94334

**Comment by Jegelewicz** [comment]
I'm guessing that is the same issue I was having in #6670

**Comment by jldunnum** [comment]
Hmm, yeah you are right they all come up when searching from the identification field

**Comment by Jegelewicz** [comment]
I think this has to do with flat and the fact that for whatever reason, flat currently doesn't include the genus for these two. Dusty says he did something, but it will take some time, so eventually, they should show up in your genus search.

**Comment by jldunnum** [comment]
Thats good, is this a wider ranging issue though? I just happened to be looking at these and noticed it. Can we do some kind of sweep to see if this happening on a larger basis?

**Comment by Jegelewicz** [comment]
@dustymc can confirm, but I think that is what is happening now.

**Comment by dustymc** [comment]
Yes, see the linked issue. If you refresh the cache for a record and it does what's expected then the problem is solved, just catching up. If it does something unexpected then I need to know about it.

**Comment by jldunnum** [comment]
Just had the same problem with Cricetulus barabensis. If I search on barabensis in the species field I get some number of results, if I search on Cricetulus barabensis in the identification field I get a lot more. 
Is this an issue for every taxon in Arctos? Do I need to somehow refresh every search? If that is the case then something needs to be reworked so that does not happen. Noone would know to do that and they shouldn't have to. We need to be able to search on any one of these fields and get the exact same result.

**Comment by jldunnum** [comment]
Ok didn't know the binomial was needed. Wasn't always that way was it? Regardless, using the binomial in the species field still doesn't return the same results as when you use the identification field. If Dusty is currently fixing the global issue then I won't stress about it now.

**Comment by dustymc** [comment]
done?
