### ISSUE TITLE
add citations video tutorial

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#6872]
I made a video of the process for adding publications and specimen citations 1 at a time. Please add it to the tutorials if it seems helpful.
Aren

https://drive.google.com/file/d/1_oita9cABlwi3iXSaXcGgK2vDec6sSVL/view?usp=drive_web

**Comment by Jegelewicz** [comment]
@amgunderson Thank you!!!

**Comment by Jegelewicz** [comment]
Addeed the tutorial to the How To.

**Comment by Jegelewicz** [comment]
This still needs to be added to the YouTube channel. @mkoo can you do that?

**Comment by Jegelewicz** [comment]
Once at YouTube - the link in the [How To](https://handbook.arctosdb.org/how_to/How-to-Create-Citations.html) should be changed to direct there.

**Comment by dustymc** [comment]
@mkoo ping?

**Comment by Jegelewicz** [comment]
@ebraker can you add to the YouTube channel?

**Comment by dustymc** [comment]
done?

**Comment by ebraker** [comment]
added to the youtube channel - @mkoo, I still don't have permissions in arctosdb.org (I can log in, I'm just no longer authorized to edit pages)
