### ISSUE TITLE
 duplicate publications

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#8202]
**Describe what you're trying to do** 

https://docs.google.com/spreadsheets/d/1njmL_GboYrV0UvBJNVTk8J-v_DktTV82F7Hed_ivt5w/edit?gid=406778936#gid=406778936 are some potential duplicate publications. The "dup" column is those that caught my eye. This isn't necessarily all of the duplicates, and I might have marked something erroneously.

Here are some that I think are actually dups and which are involved in citations. 

```
 guid_prefix | publication_id |  c  
-------------+----------------+-----
 BYU:Herp    |       10001845 |   1
 MSB:Host    |       10007061 |   7
 MSB:Mamm    |        1000099 |   4
 MSB:Mamm    |        1000105 |   8
 MSB:Mamm    |       10004380 |   6
 MSB:Mamm    |       10004425 |  29
 MSB:Mamm    |       10004574 |   8
 MSB:Mamm    |       10006748 |   3
 MSB:Mamm    |       10008582 |   1
 MSB:Mamm    |       10009301 |   1
 MSB:Para    |       10007061 |  11
 MSB:Para    |       10012064 |   1
 MVZ:Bird    |       10000301 |   3
 MVZ:Bird    |       10000302 |   1
 MVZ:Bird    |       10000325 |   1
 MVZ:Bird    |       10000328 |   2
 MVZ:Bird    |       10000404 |   2
 MVZ:Herp    |       10001760 |   1
 MVZ:Herp    |       10001845 |  15
 MVZ:Herp    |       10004876 |   9
 MVZ:Mamm    |       10008131 |   6
 UAM:Bird    |       10006856 |   1
 UAM:Herb    |        1000120 |   3
 UAM:Herb    |        1000161 |   9
 UAM:Mamm    |             62 |   5
 UAMObs:Ento |       10006002 |   1
 UAMObs:Ento |       10006030 |  15
 UAMObs:Ento |       10006048 |  12
 UAMObs:Ento |       10010231 |  31
 UAMObs:Ento |       10012227 |   1
 UCM:Bird    |       10007095 |   3
 UCM:Herp    |       10007752 |   1
 UCM:Herp    |       10009587 | 299
 UCM:Herp    |       10011156 |   5
 UCM:Obs     |       10009334 |   1
 UCM:Obs     |       10009335 |   1
 UMNH:Mamm   |       10007974 |  53
 UTEP:ES     |       10007918 |   1
 UTEP:ES     |       10008377 |  14
 UTEP:ES     |       10008926 |   4
 UTEP:ES     |       10008951 |   1
 UTEP:Herp   |       10001760 |  16
 UTEP:Herp   |       10008795 |  12
 UTEP:Herp   |       10008948 |  12

```

 @amgunderson
 @jldunnum
 @msbparasites
 @AdrienneRaniszewski
 @campmlc
 @DerekSikes
 @StefanieBond
 @mlbowser
 @ccicero
 @mkoo
 @cjconroy
 @atrox10
 @mvzhuang
 @ebraker
 @camwebb
 @kderieg322079
 @byuherpetology

Please let me know if I can help some way, or if we could somehow better prevent duplicates. For scale, there are 10655 publications in Arctos at the moment and I think 76 of them (~half of which contain citations) might be duplicates - i don't think that's too terrible, but we're still not getting proper credit to some folks (including some of "us").

**Comment by cjconroy** [comment]
What's the best practice? I have one on there shared with MSB. I can add my specimens to the MSB created pub since they have more attached specimens, but then do we delete my version of the publication?

**Comment by dustymc** [comment]
>best practice?

Just what you describe - do whatever's necessary to remove duplicates so that the authors get proper credit, anyone following citations ends up looking at all of the data recorded in Arctos, etc.

And I'm happy to move citations or whatever, let me know how I can help.

**Comment by jldunnum** [comment]
One would hope this could be done in an automated fashion. Individually relinking records to pubs already in Arctos doesn't seem like a great option given that there are literally thousands of pubs still waiting to be added and have records linked.


______________________________________________________________
Jonathan L. Dunnum Ph.D. (he, him, his)
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
Research Assistant Professor (LAT)
Department of Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

Chair, Systematic Collections Committee, American Society of Mammalogists
Latin American Fellowship Committee, ASM

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by cjconroy** [comment]
If you want to move MVZ citations from pub 10008131 to 10004425 and then destroy 10008131, that would be swell. I tried adding the DOI to 10004425 but that wasn't possible, probably since the other pub already has the DOI.

**Comment by dustymc** [comment]
>10008131 to 10004425

done

**Comment by kderieg322079** [comment]
Deleted 10007972 since it didn't have any citations but 10007974 did. UMNH should be good now

**Comment by ebraker** [comment]
Most of the pubs tied to UCM citations do not appear to be duplicates (many are different articles within the same journal). I deleted three that were pure duplicates  - in all cases, the duplicate did not have associated citations - and removed these pubs from your spreadsheet.

Other actions for @dustymc :

10001845 - Keep
10011156 - Move UCM records to 10001845 and delete pub

10000404 - suggest adding MVZ records to 10007095 and delete pub
10007095 - Keep: this one has media attached

**Comment by dustymc** [comment]
>do not appear to be duplicates

Not surprising, and I probably missed some that are - hence this plea for help, and thanks!


> 10011156 - Move UCM records to 10001845 and delete pub

done


>10000404 - suggest adding MVZ records to 10007095 and delete pub

I went the other way - it's easier to move media than DOIs, and the one with a DOI had a matching title.

**Comment by DerekSikes** [comment]
I fixed the one apparent duplicate situation in UAMObs:Ento, thanks!

**Comment by camwebb** [comment]
UAM:Herb, cleaned two unused duplicates as above.

**Comment by campmlc** [comment]
We are trying to fix some duplicate publications at MSB which are attached to projects. We are unable to remove them from the project, and get no error as to why.  	 
            Keep                    10012064	RauschandMargolis1969
Delete from Project	        10005225	RauschandMargolis1969
	    Keep                     10005348	RauschandRausch1993
Delete from Project    	 10005331	RauschandRausch1993
 Keep  	                         10006531       SalazarBravoetal2003
Delete from Project	         10004944	SalazarBravoetal2003
Keep                                10006748	Walkeretal2014

**Comment by campmlc** [comment]
Here's another problem: 
Trying to remove this duplicate publication https://arctos.database.museum/publication/10007037 . It has a DOI but no attached citations or sensu. When we go to the edit page, we see nothing - all blank, so can't remove the DOI. When we try to delete, we get the message that syntax error at end of input Position 52".

**Comment by dustymc** [comment]
>get no error 

Mind telling me what happens then? (I'm imagining you hoping really hard that it'd just go away...)

>10012064 - 10005225 

merged - and it'd be useful if you could just give me the duplicate pairs, I go one way or the other for lots of reasons.


>10005348 10005331

merged

>10006531  10004944 


merged

>edit page, we see nothing 

Bug fixed in next release, https://arctos.database.museum/publication/10007037 deleted

**Comment by campmlc** [comment]
> > get no error
> 
> Mind telling me what happens then? (I'm imagining you hoping really hard that it'd just go away...)

From the project edit page, we go to the pub and click "Remove Publication". The screen "flickers" as though something is happening - but the pub is still there attached to the project. No error message.

**Comment by dustymc** [comment]
I can't replicate, I just zapped a bunch in test without any hiccup, but there was a massive attack this morning, it's possible you were caught up in that.

**Comment by campmlc** [comment]
Here's another set of duplicates, one with citations, the other linked to a project:
<div ccp_infra_version='3' ccp_infra_timestamp='1729905029253' ccp_infra_user_hash='2688768491' ccp_infra_copy_id='7ab8f33b-7fa4-4ca4-8286-6c1e556362dc' data-ccp-timestamp='1729905029253'><html><head><meta name=ProgId content=Excel.Sheet><meta name=Generator content="Microsoft Excel 15"><style>table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
td
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	text-align:general;
	vertical-align:bottom;
	border:none;
	white-space:nowrap;
	mso-rotate:0;}
.xl63
	{color:black;
	background:red;
	mso-pattern:black none;}
.xl65
	{color:black;
	text-align:right;
	background:red;
	mso-pattern:black none;}
.xl81
	{background:red;
	mso-pattern:black none;}
.xl82
	{text-align:right;
	background:red;
	mso-pattern:black none;}
</style></head><body link="#1155CC" vlink="#1155CC">
10011177 | DuboisandRausch1950
-- | --
10005121 | DuboisandRausch1950

</body></html></div>

**Comment by dustymc** [comment]
>10011177 - 10005121 

done

**Comment by campmlc** [comment]
@dusty I believe all MSB Mamm, Para, and Host are fixed. Can you check if there are any other MSB left?

**Comment by dustymc** [comment]
That's still not me.

>Can you check

Not really, please see previous comments, everything from me is just the most-obvious stuff that's jumped out at me (as part of https://github.com/ArctosDB/dev/issues/41), this really needs attention from more-familiar users. I did pull new "near-not-unique short citation" data and left it in the "1028" tab of the linked spreadsheet. I can pull any other sort of data, just let me know what might be useful.

**Comment by campmlc** [comment]
I have a student working on this right now, and she will be gone at the end of the semester. If there is any way we can find other potential MSB dups, we have the ability to solve some now. Otherwise who knows. I really don't know how to search for potential duplicates unless @dustymc can provide us a list. ?

**Comment by dustymc** [comment]
>If there is any way 

Get someone familiar with the material to have a scan though is my only idea, but there's not much limit on the ways in which a person might have managed to hide data so there's not much of a universal prescription for finding such data. Hopefully you know more about what was going on in your collection than I can glean from the most-apparent errors and somehow follow that to somewhere productive.

>provide us a list

I put the latest in the spreadsheet, but eg I've noticed a number of typos in these data, and such things in inconvenient places will completely bypass the logic I used to generate my list. If you have some other list in mind just let me know what you want included/how to make it and I'll do so, as I've offered just above.

**Comment by campmlc** [comment]
> > If there is any way
> 
> Get someone familiar with the material to have a scan though is my only idea, but there's not much limit on the ways in which a person might have managed to hide data so there's not much of a universal prescription for finding such data. Hopefully you know more about what was going on in your collection than I can glean from the most-apparent errors and somehow follow that to somewhere productive.

MSB has literally thousands of publications dating back decades for multiple divisions - there is no "someone" familiar to do a scan through. I believe once we have agents associated with publications that might become easier (maybe) going forward, but it would be much easier if we could track via collection or institution. Otherwise this is a futile endeavor.
> 
> > provide us a list
> 
> I put the latest in the spreadsheet, but eg I've noticed a number of typos in these data, and such things in inconvenient places will completely bypass the logic I used to generate my list. If you have some other list in mind just let me know what you want included/how to make it and I'll do so, as I've offered just above.
Unfortunately, no.  Creative ideas welcome.

**Comment by dustymc** [comment]
>literally thousands

I was curious:

```
 institution_acronym |  c   
---------------------+------
 CRCM                |    1
 Arctos              |    1
 ACUNHC              |    1
 DGR                 |    3
 ACBC                |    3
 USNPC               |    4
 HWML                |    5
 ASNHC               |    5
 KWP                 |    6
 TCDGM               |    8
 UWYMV               |   11
 UA                  |   20
 UWBM                |   32
 ALMNH               |   39
 KNWR                |   48
 BYU                 |   57
 MLZ                 |   66
 UMNH                |   67
 CHAS                |   68
 UCM                 |  148
 DMNS                |  283
 NMMNHS              |  353
 UTEP                |  374
 MSB                 |  619
 MVZ                 |  970
 UAM                 | 1266
```

>if we could track via collection or institution

Not sure what that means, but it's probably best cast as an issue or discussion.

>once we have agents associated 

Always have been? (Unless you mean captured 'whoduit', in which case we recently have that, but I have no way to populate it for legacy data.)

**Comment by campmlc** [comment]
Cool. Not as bad as it could be, but we still have to s pending load. Can we get the csv of MSB associated pubs?

**Comment by dustymc** [comment]
>the csv 

PLEASE be specific, what data do you need? "Publications" might involve very close to an infinite number of possibilities from here, I need some help.

Also in case it wasn't clear, my summary above is from citations - that may or may not have anything to do with what you're looking for/consider yours.

**Comment by ebraker** [comment]
@dustymc - I happened upon a duplicate set of pubs:

https://arctos.database.museum/publication/10009865
https://arctos.database.museum/publication/10007282

Can you merge into 10007282 please? The media from 10009865 can be deleted as well (it is a BHL link that is also present in 10007282).

**Comment by dustymc** [comment]
10009865 - 10007282 - done thx
