### ISSUE TITLE
container type unknown

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#8460]
Help us understand your request (check below):

- [x] other

**Describe what you're trying to do** 

Container type unknown [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcontainer_type#unknown) ...

>we've attached a barcode to something but were unable to identify the thing being barcoded…

... exists and has a handler to prevent movement. I don't think that sort of eternal purgatory is sustainable, so I propose we:

* transfer these to some other type and remove the strange type from the code table, or
* just drop the extra controls, leaving usage up to the collections

Let me know how I can help if we want to clean up, or if there's no movement here I'll proceed with dropping the controls in a few weeks.

Usage summary:

```
arctosprod@arctos>> select institution_acronym, count(*) c from container where container_type='unknown' group by institution_acronym;
 institution_acronym |   c   
---------------------+-------
 DMNS                |     1
 MSB                 |     5
 MVZ                 | 75988
 UAM                 | 30180
(4 rows)
```

**Comment by campmlc** [comment]
I support dropping the controls, but this has a greater impact on MVZ and UAM.

**Comment by dustymc** [comment]
Adding to AWG for hopeful less-awful resolution.

**Comment by mkoo** [comment]
added to the agenda but maybe likely we just need to elevate to the collections' attention

**Comment by ccicero** [comment]
@dustymc will provide data for us to look at per AWG meeting today.

**Comment by dustymc** [comment]
Data:

[temp_unknown_and_child.csv.zip](https://github.com/user-attachments/files/19016464/temp_unknown_and_child.csv.zip)

**Comment by mkoo** [comment]
thanks Dusty!
Looks like the majority of MVZ with labels that contain 'tissue' can be changed to type=```vial``` (https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcontainer_type#vial) Dont you agree @ccicero @cjconroy @atrox10 ?
The others with no labels (NULL) are true unknowns (precatalog stuff, right?)

**Comment by campmlc** [comment]
I have fixed all but two MSB ones - I'm working on figuring those out.

**Comment by ccicero** [comment]
@dustymc @mkoo @cjconroy @atrox10 

No, not yet. At a quick glance I see two types of issues with MVZ data:

1) Legacy tissues where there is no barcode and a C1 label like "MVZ Birds 166584 tissue". These had old 'container' labels (e.g., 166584.1) and paths from our first (?) migration? I've checked a bird and a mammal and the tissue is either missing or discarded, but it would help to get the data again for those (where C1 label is not null) and which include GUID_Prefix and disposition. I think those may be vials that were not found when we moved everything to LN2 and barcoded vials. Example: https://arctos.database.museum/guid/MVZ:Bird:166584

2) A larger number of records have just a label (also legacy) but no C1 label.  I checked one (172896.1) and can't figure out the specimen. I searched birds, mammals, and herps for that number. 
Bird - tissue has a container type and full path (https://arctos.database.museum/guid/MVZ:Bird:172896)
Mamm -  tissue has a container type and full path (https://arctos.database.museum/guid/MVZ:Mamm:172896)
Herp - no tissue indicated, just whole organism (https://arctos.database.museum/guid/MVZ:Herp:172896)

Can you send those data again in a separate query with GUID_Prefix and disposition and any other info that will be useful to track down what's going on? 

Thanks.

**Comment by dustymc** [comment]
> include GUID_Prefix 

[temp_unknown_and_child(2).csv](https://github.com/user-attachments/files/19016893/temp_unknown_and_child.2.csv)

>but no C1 label.

Then there should be no children - which you can confirm in the UI

<img width="1681" alt="Image" src="https://github.com/user-attachments/assets/19b1b52e-294f-4cf8-98e4-6dae9047fe33" />

**Comment by ccicero** [comment]
@dustymc @mkoo @cjconroy @atrox10 

Doing this in chunks for the MVZ records. Attached are two files:

1) Records (n = 7939) where 'tissue' is in the C1_LABEL field. Those should be changed to container type = 'cryovial' (file name 'container_type_cryovial'
2) Subset of those records (n = 194; Bird = 56, Mamm = 138) that have a disposition of 'in collection' but no barcode or path. I think those are old legacy ones that were not found when barcoding and moving MVZ tissues into LN2. Can we change the disposition for those to 'missing' ? file name 'container_type_cryovial_incollection'

[container_type_cryovial.csv](https://github.com/user-attachments/files/19017147/container_type_cryovial.csv)

[container_type_cryovial_incollection.csv](https://github.com/user-attachments/files/19017151/container_type_cryovial_incollection.csv)

**Comment by ccicero** [comment]
Second chunk for MVZ: Records (n = 451; Bird = 11, Mamm = 172, Herp = 268) where C1_LABEL does not contain 'tissue': these are whole organisms, embryos, tail tips, etc. Some may be cryovials, but others not ???

@mkoo @cjconroy @atrox10 These will need to be checked and fixed individually by checking the collection. I will take care of the birds. Chris and Carol will need to deal with the mammals and herps.

[container_type_unknown_not_tissue.csv](https://github.com/user-attachments/files/19017591/container_type_unknown_not_tissue.csv)

**Comment by ccicero** [comment]
The remaining MVZ records (n = 67,596) don't appear to have children (no associated GUID). I'm not checking everyone through the UI, but I did some spot checking. @dustymc can you confirm that the ones in the list without a GUID are childless?

@mkoo If that's the case, I think those can just be deleted - ???

**Comment by ccicero** [comment]
Thanks! @dustymc 

@mkoo All of the MVZ 'containers' with no contents (label formatted as catnum.1) are a legacy issue for reasons that I don't recall right now. I think we can just delete those containers as they are not associated with any barcode or cataloged record. OK?

**Comment by cjconroy** [comment]
The vast majority of mine that aren't disposition=missing are from embryos of woodrats collected by Jim Patton. They show two parts. One is part = embryo and it is scanned into a tissue box. The other is also embryo, but has 95% ETOH in the remark field and no preservation attributes. I am hoping this is some kind of legacy weirdness and can be cleaned up. But, I will consult Jim and see if there is something in a jar.

**Comment by ccicero** [comment]
@dustymc I talked with @mkoo and we agree that all of the ones with no contents (not associated with a barcode or cataloged item) can be deleted.

**Comment by dustymc** [comment]
> can be deleted.

Well that was WAY more "fun" than anyone ought to have on a sunny Friday afternoon, but done.

Here's what's left.

[temp_unknown_and_child(3).csv.zip](https://github.com/user-attachments/files/19034395/temp_unknown_and_child.3.csv.zip)

```

arctosprod@arctos>> select institution_acronym,count(distinct(container_id)) from temp_unknown_and_child group by institution_acronym;
 institution_acronym | count 
---------------------+-------
 DMNS                |     1
 MSB                 |     3
 MVZ                 |   451
 UAM                 | 30522

```

@megulbranson help?

**Comment by campmlc** [comment]
I converted two of the MSB mystery ones to "tag" although we don't know what they are as they appear to be associated with the wrong part. We'll try to sleuth that out. 

The third MSB one is "DGRDEL", with the label "DGRDELETE", which is a virtual container for barcodes that need to be deleted. Since we now have the option of a virtual container type, I can convert unknown to virtual. BUT, I'd like to be able to delete all the child barcodes and their children etc. None are associated with parts, and all are barcodes that were on empty containers that were disposed of (worn out freezer boxes, racks given to research labs etc). Can I do this, or does @dustymc get to have even more "fun" on Friday evening? :(

**Comment by ccicero** [comment]
Yay! Working on the remaining MVZ ones.

**Comment by ccicero** [comment]
@dustymc @mkoo I think that I've fixed all of the MVZ:Bird issues that were remaining. The rest need to  be fixed by @cjconroy @atrox10

**Comment by cjconroy** [comment]
I've talked to Jim Patton and looked at the MVZ specimens. They are all (except one) a tiny embryo, each in their own tube. They do not have a part in our fluid collection. I don't know what the second line of embryo is for which has no container. Is it possible the embryo part with remark of 95% ETOH is how the part was originally entered ~20 years ago and Arctos converted it to the other embryo part, but did not delete the original part? Could they be removed in some easy way? There's over 100 of them.

**Comment by ccicero** [comment]
@cjconroy Not all of the ones are embryos, see attached spreadsheet for just the mammals. If all of the embryo parts with unknown container type (and remarks contains '95% ETOH') can be deleted, let @dustymc know and he can do that. 

I'm not sure what you mean about the exception, is it in a cryovial with another embryo or in a different type of container? Which specimen is that one?

You will need to provide guidance on what to do with the other parts that are not embryos and have unknown container types.

[MVZMamm_unknown_container.xlsx](https://github.com/user-attachments/files/19233875/MVZMamm_unknown_container.xlsx)

**Comment by cjconroy** [comment]
Dusty, I would say all the ones that have a part like this can be deleted. Just this part. Not the embryo part that is scanned into a box.

embryo | unchecked; partial | in collection | 1 | [ ] 215916.1 (unknown) | [ ] Museum of Vertebrate Zoology (institution)←[ ] 215916.1 (unknown)
-- | -- | -- | -- | -- | --

I'd say all the other parts can all be given to cryovial. They are all little things that were originally in vials, but are now missing, used up, on loan, or discarded. 
Thanks,
Chris

**Comment by dustymc** [comment]
@cjconroy I think you want to 

* delete the parts in this CSV, then
* delete the 'unknown'-type containers which held them (container_id==p1id)

Please confirm or enlighten.

[temp_maybe_this.csv](https://github.com/user-attachments/files/19249168/temp_maybe_this.csv)

**Comment by cjconroy** [comment]
I think that works. There is one specimen, MVZ:Mamm:196725, for which this discarded part is the only part for that specimen. If that is allowable, then the record still records that species at that place and time. The rest all have the correct version of the part, and other parts.

**Comment by dustymc** [comment]
>works

Done.

Fresh data:

[temp_unknown_and_child(4).csv.zip](https://github.com/user-attachments/files/19251720/temp_unknown_and_child.4.csv.zip)

> all the other parts can all be given to cryovial.


Confirm that for these data...

[temp_maybe_this_2.csv](https://github.com/user-attachments/files/19251742/temp_maybe_this_2.csv)

... I should update container_type of P1ID container to 'cryovial'

**Comment by AJLinn** [comment]
Are you able to see what collection(s) the UAM barcodes are associated with?

**Comment by AJLinn** [comment]
>  UAM:EH      |     1

Fixed.

**Comment by amgunderson** [comment]
These are relics of when we used catalog numbers as barcode numbers. If it's possible, these parts could all be moved to their next higher container. I am pretty sure I can figure that out myself.

**Comment by amgunderson** [comment]
I tried to bulk edit container to change the container type from unknown to tag but they were all returned as "barcode not resolved". They can be edited one by one without a problem so I don't know why the bulk option fails. These are still tracking the location of their parts so I do not want them to disappear. Is it a problem to have container type = unknown ?

**Comment by dustymc** [comment]
>barcode not resolved

Your institution_acronym is UAM - or I'm happy to update, just need specifics.

>Is it a problem to have container type = unknown ?

Not necessarily, see first comment, I'm just trying to get out of the limbo we've apparently been in since this was created to address whatever it was (but leaving the bits laying around doesn't seem optimal..).

**Comment by amgunderson** [comment]
Okay, I'll go with that and see how it works for 1,000 at time. Thanks

**Comment by dustymc** [comment]
Fresh data:

[temp_unknown_and_child(5).csv](https://github.com/user-attachments/files/19397571/temp_unknown_and_child.5.csv)

Summary:

```

arctosprod@arctos>> select institution_acronym,count(distinct(container_id)) from temp_unknown_and_child group by institution_acronym;
 institution_acronym | count 
---------------------+-------
 DMNS                |     1
 MVZ                 |   274
 UAM                 | 17472
(3 rows)

Time: 17.904 ms
arctosprod@arctos>> select guid_prefix,count(distinct(container_id)) from temp_unknown_and_child group by guid_prefix;
 guid_prefix | count 
-------------+-------
 DMNS:Bird   |     1
 DMNS:Mamm   |     1
 KWP:Ento    |     1
 MVZ:Herp    |   199
 MVZ:Mamm    |    56
 UAM:Ento    |     1
 UAM:Herp    |     2
             | 17488

```
@amgunderson @megulbranson this is now mostly unused (no contents) UAM containers, help?

**Comment by amgunderson** [comment]
From the few I looked at, the specimens whose catalog numbers were used as barcodes have been scanned into proper dummy barcodes - so those can be deleted. Another large series are from large box labels we made when moving wolf and lynx into boxes, they were made in Arctos but never printed IRL - so those can be deleted. We will never use these. All our current barcodes are claimed and called container labels if nothing else.
So if it really is type = unknown, contains nothing, and belongs UAM:Mamm it can be deleted.

**Comment by dustymc** [comment]
>can be deleted


[temp_uam_unk_nc_datadump.csv.zip](https://github.com/user-attachments/files/19436409/temp_uam_unk_nc_datadump.csv.zip)

I switched the three containers used by https://arctos.database.museum/accn.cfm?action=edit&transaction_id=360 to tag.

The rest are done.

**Comment by dustymc** [comment]
done
